"""update users table

Revision ID: 528d228a45bf
Revises: af6653aa6bfd
Create Date: 2024-04-05 17:54:15.651099

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '528d228a45bf'
down_revision: Union[str, None] = 'af6653aa6bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
